steps:
  # Step 1: Build the Docker container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/legalease-ai:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/legalease-ai:latest'
      - '--build-arg'
      - 'GOOGLE_AI_API_KEY=AIzaSyCaUQrPDlB_6CtZzc8VmnoxRBsYZ0gWLDk'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyB4MH5Ts3YT2FZNB4YFxX1m_CnT89R20d8'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=legalease-ai-566e9.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=legalease-ai-566e9'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=legalease-ai-566e9.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=258644695088'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:258644695088:web:a4f0ae89c4a5b7c74f5a9e'
      - '--build-arg'
      - 'NODE_ENV=production'
      - '.'
    timeout: '900s'

  # Step 2: Push the container to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/legalease-ai:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/legalease-ai:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'legalease-ai'
      - '--image=gcr.io/$PROJECT_ID/legalease-ai:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=60'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NEXTAUTH_URL=https://legalease-ai-591134707706.us-central1.run.app'

# Save the images
images:
  - 'gcr.io/$PROJECT_ID/legalease-ai:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/legalease-ai:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
